# Exploration

```{r xp-setup}
library(tidyverse)
source(here::here("R/zzz.R"))
source(here::here("R/extract.R"))

d <- load_qx_surveys()
```

## Inclusion Group Overviews

```{r xp-client-data}
d_client <- d |> 
  filter(name |> str_detect("Client")) |> 
  unnest(data) |> 
  filter(
    is.na(Q_RecaptchaScore) | (Q_RecaptchaScore >= .9), 
    Q_BallotBoxStuffing == "", 
    DistributionChannel != "preview", 
    gta_screener_1 %in% c("", "Toronto, ON, Canada"), 
    Progress == 100
  )
```

### Client Survey

```{r xp-igo-client-survey}
#| label: tbl-xp-igo-client-survey
#| tbl-cap: "Inclusion Group Representation in Client Survey"

d_client |> 
  count(igs_lang_fols)

d_client |> 
  mutate(
    demo_age = lubridate::ymd(glue::glue("{igs_dob_year}-{igs_dob_month}-15")) |> 
      lubridate::interval(lubridate::as_date(EndDate)) |> 
      lubridate::as.period() |> 
      lubridate::year(),
    ig_youth = demo_age < 30,
    ig_newcomer = case_when(
      is.na(igs_immigrant) ~ NA, 
      igs_year_landed %in% "2019 or later" ~ TRUE, 
      TRUE ~ FALSE
    ), 
    ig_disability = igs_disability == "Yes", 
    ig_francophone = case_when(
      is.na(igs_lang_first) ~ NA, 
      igs_lang_first == "English" ~ FALSE,
      igs_lang_first == "French" ~ TRUE,
      igs_lang_english %in% "Yes" & igs_lang_fols %in% c("English", "Both") ~ FALSE, 
      TRUE ~ TRUE
    ), 
    ig_racialized = , 
    ig_indigenous = igs_indigenous == "Yes", 
  ) 

d_client |> 
  select(matches("^igs")) |> 
  labelled::var_label()


```