# Themes

:::{.callout-note}
## Interpretive Guidance

- **What is this?** This page summarizes the key themes that have emerged from our analysis of the survey data collected about the experiences of clients, staff, and stakeholders of Employment Services (ES) in Ontario. It is subject to the same disclaimer as the rest of this exploratory analysis, and should be read as a provisional interpretation of the data. 
- **Why is this?** This page is intended to support meaningful discussion of the preliminary findings and act as a guide for self-guided navigation of the exploratory tables, charts, and text that make up the rest of the section. 
- **Inclusion Groups (IGs)**: This analysis centres the experiences and perspectives of seven inclusion groups: Indigenous persons (IND), Francophones (FRA), Racialized persons (RAC), Persons experiencing Disability (DIS), Newcomers (NEW), and Youth with higher support needs (YTH). These groups are not mutually exclusive, and many survey respondents belong to more than one group. Throughout this summary, these groups are referred to by their abbreviations, not to diminish their complexity, but to make the text more readable and navigable.
- **Generalizability**: The findings presented here are based on non-random samples of clients, staff, stakeholders, and un/underemployed Ontarians. The results described here are therefore not, strictly speaking, generalizable to the broader populations from which those samples were drawn. 
:::

## Notable Demographics

### Prevalence of Newcomers

**Newcomers are a key demographic for ES in Toronto.**

Compared to the population of Toronto, Newcomers (NEW) are over-represented among the clients we reached, both in the samples as a whole and across all other IGs save IND and DIS. Totals _and_ IG-specific findings should be read with this in mind, and while our sampling design doesn't allow us to make general claims about the extent of that over-representation in the broader population of ES clients, the directional finding _that_ NEW are over-represented in the population of ES clients is uncontroversial within the WCG team or the SPO staff we have consulted. 

- NEW is by far the most represented IG in our client sample (@tbl-xp-client-es-ig-rep). 
Of the other IGs, NEW is a minority of only two (IND and DIS). 
Of the FRA or RAC clients we reached, roughly three quarters are also NEW. 
More than half of FRA clients are both NEW and RAC. 
- As of the 2021 Census, roughly half of Toronto's population weren't born in Canada, though only 7% of Toronto's population fit our definition of NEW---much lower than our client sample (62%) and our panel sample (45%).
- The upshot is that when we are describing the perspectives of FRA (76% NEW), RAC (74% NEW), YTH (61% NEW), and SA (53% NEW) clients, we are largely describing perspectives formed at the intersection of those identities with the newcomer experience (@fig-xp-client-es-intersections).
- Anecdotal evidence from the WCG team and SPO staff supports the conclusion that NEW are in fact over-represented among ES clients in Toronto, so we are confident in the direction of this finding, if not in the specific magnitude of their over-representation.

### Social Assistance Recipients

**S-OW and S-ODSP ES clients are closer to the labour market than expected**

We observe surprisingly high rates of employment, and surprisingly high annualized earnings among both S-OW, and S-ODSP clients we reached. While this is likely driven at least in part by sample design and data quality issues, it may be the case that ES in Toronto isn't reaching the members of these groups who are most distant from the labour market. 

- The group of social assistance recipients we reached reported surprisingly high employment rates in both the client survey (S-OW: 70%, S-ODSP: 85%) and panel survey (S-OW: 42%, S-ODSP: 40%) and average annualized employment earnings (@tbl-xp-client-es-lfs, @tbl-xp-panel-lfs)
- Compared to the average employed respondent, employed members of the SA group are much more likely to be employed in casual work, suggesting that while they may be employed, their jobs are relatively precarious(@tbl-xp-client-es-job-precarity, @tbl-xp-panel-job-precarity)
- If these figures are accurate, they suggest that the SA Ontarians and ES clients we reached may not be representative of the broader population of SA recipients in Ontario, who are more likely to be unemployed and to have lower incomes.
- In spite of potential data quality issues, it is plausible that SA recipients who engage with ES may, as a subgroup of SA clients overall, be closer to the labour market than the broader population of SA recipients. If this is the case, it would suggest that ES isn't reaching the SA recipients most distant from the labour market. 
- This aligns with anecdotal reports from the WCG team, who have highlighted the challenges of engaging with "stream C" clients in general.

### Education

**The ES clients we reached are highly educated, though many attained their credentials outside of Canada**

- Compared to the general population of Ontarians, our sample is highly educated. 
Whereas roughly a third of Ontario's working age population has a Bachelor's degree, 39% of the clients (@fig-xp-client-es-edu-ecdf) and 54% (!!!) of panel participants (@fig-xp-panel-educ-ecdf) we reached reported having at least a Bachelor's degree. 
- Of note, however, and fitting with high incidence rates of NEW in both samples many of those credentials were obtained internationally. About half of university educated clients and panel participants reported having obtained their highest degree outside of Canada.


## Engaging Inclusion Groups

Across IGs, our analysis suggests that the highest impact opportunities for increasing engagement lie in building a better reputation for effective service delivery by improving client satisfaction. 
From here, we observe a split between one set of IGs (IND, DIS, and SA) whose members are virtually all aware of ES, and so aren't likely to be moved to engage by campaigns that simply raise awareness, and a second set (NEW, YTH, and RAC) whose members are less likely to be aware of ES, and so might be more effectively engaged by campaigns that raise awareness.

### A _Mixed_ Reputation

**The reputation of ES in Toronto is likely harming engagement more than it is helping**

- NPS is negative among clients we reached for the panel survey (-14) and client survey (-10), which tells us that word-of-mouth is likely a slight drag on overall engagement, and that meaningful improvements in client satisfaction could have corresponding positive effects on engagement. (@tbl-xp-client-nps, @tbl-xp-panel-es-nps)
- While staff reported broad confidence in their readiness to serve a diverse array of clients, they indicated the most doubt about being equipped to serve DIS, IND, and S-ODSP clients (@tbl-xp-staff-challenge)

### Opportunities to do More

**ES can reach more Torontonians by improving service quality and raising awareness among NEW, YTH, and RAC**

- Our analysis suggests convincing aware but unengaged Ontarians that ES can help them achieve their goals and clearly indicating how to access services would move some to engage with ES. Among panel respondents who reported awareness of but not engagement with ES, the most commonly cited reasons for not engaging were, in descending order of frequency (@tbl-xp-panel-es-opt-out): 
  1. I don't believe ES will help me achieve my goals (particularly within DIS)
  2. I am happy with my current employment situation (particularly within SA)
  3. I don't know how to access ES (particularly within IND and NEW)
- If we believe that ES has a reputation problem across IGs, it follows that service delivery improvements that increase client clarity, trust, and satisfaction would result in increased engagement across all groups, but particularly among those who are already aware of ES but not engaged.
- Responses to the panel survey suggest that marketing would reach the most IG members on high-traffic digital platforms like Youtube and Instagram (@tbl-xp-panel-outreach-digital), 
though some physical locations like doctor's offices and libraries remain potentially useful (@tbl-xp-panel-outreach-physical)


## Serving Inclusion Groups

According to the staff and stakeholders we reached, ES clients from across the inclusion group spectrum share many labour market barriers, success factors, and necessary social supports in common. 
Staff emphasized a similar distribution of key challenges they experience when serving clients from different inclusion groups. There are, however, some key differences that are worth noting. 

### Communication and Trust

**Communication, trust, and understanding are key challenges for ES clients, particularly for IND clients**

- Both client and panel surveys provide strong evidence that the reputation is worst among IND clients. Among respondents to the panel survey, IND clients have the lowest NPS (-69), with 69% of respondents identified as detractors, and none identified as promoters. 
- In the panel survey, IND respondents reported disproportionate experiences of gaps in communication, feelings of being misunderstood, and a lack of trust in the intentions of the caseworker. They responded "Always" or "Often" less often than average when asked to recall how often they felt each of the following during their ES journeys (@tbl-xp-panel-es-ovr):
  + When I ask questions, I get satisfactory answers quickly: 38% vs 56%
  + I have confidence that my caseworker will support me to get a job: 44% vs 52%
  + My caseworker is encouraging and motivational: 38% vs 58% 
- Results of the client and panel survey disagree about the perspective of S-ODSP and S-OW clients, with the client survey suggesting that they are among the least satisfied groups (S-OW: -20, S-ODSP: -38), but the panel survey suggesting that they are among the most satisfied groups (S-OW: 8, S-ODSP: 12). 
- In the panel survey, S-OW and S-ODSP clients reported understanding, being understood by, and trusting the system more than average, while the inverse is true in the client survey. 

### Challenges

**Working with S-OW and IND clients, staff find it most challenging to maintain engagement and support completion. For all other groups, connecting clients with employment opportunities is the most challenging aspect of their work.**

@tbl-xp-staff-challenge

- Staff most commonly reported that they find connecting clients with employment opportunities to be the most challenging aspect of their work with all inclusion groups except for IND and SA (OW), for whom the most commonly reported biggest challenge is maintaining client engagement, followed by connecting clients with employment opportunities. 
- I want to zoom in on the reported difficulty of maintaining engagement with IND clients, as it is colocated with the lowest (most negative) client NPS scores in our sample, and with the highest rates of distrust and misunderstanding. 

### Barriers 

@tbl-xp-stakeholder-barriers, @tbl-xp-staff-barriers

- According to the staff and stakeholders we reached, IGs share a similar distribution of the barriers about which we inquired with the exception of FRA (who staff and stakeholders seemingly tend to percieve as less barriered than the other groups) 
- Discrimination, either in hiring or on-the-job, was flagged as high-impact barrier in a majority of cases across all groups except FRA and SA (OW)
- DIS, IND, RAC, and SA (ODSP) experience high rates of discrimination both in hiring and on-the-job
- NEW and YTH are more liable to experience discrimination in hiring than on-the-job
- Across all groups, staff flagged missing employability skills as a high-impact barrier more frequently flagged missing technical skills

### Success Factors 

@tbl-xp-stakeholder-job-factors, @tbl-xp-staff-job-factors

- Employer training and skills development opportunities were most frequently flagged as critical across all groups
- Flexible hours especially important for IND, DIS, and SA (ODSP)
- Having colleagues with whom they can identify is most important for IND and SA (ODSP)
- Workplace accommodations are understandably most important for DIS and SA (ODSP)

### Critical Supports
@tbl-xp-stakeholder-social-supports, @tbl-xp-staff-social-supports

- Across inclusion groups and organizations, staff and stakeholders emphasized the value of skills development, flagging the importance of technical skills training, employability skills training, and coaching or mentoring for the achievement of sustainable employment
- Support for disclosing needs and requesting accommodations was flagged as "absolutely necessary" in a majority of responses for DIS, SA (ODSP), and IND 
- English language training was highlighted as a critical support for NEW
