name: Deploy S3

on: 
  push: 
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps: 
      - uses: actions/checkout@v3
      - name: Deploy
        uses: reggionick/s3-deploy@v4 
        with: 
          folder: docs
          bucket: ${{ github.event.repository.name }}
          bucket-region: us-east-2
          delete-removed: true
          no-cache: true
          private: true